### ISSUE TITLE
Job opportunity

### ISSUE THREAD

**Issue by MadhuDara** [Saketh-Chandra/Saketh-Chandra#1]
Hi,

This is Madhu from proximate technologies.

I’m reaching out to see if you’d be interested in a job opportunity. Please let me know if you are available to discuss.

You can reach me out @469-731-3979 or
#mail: madhu@proximatetech.com

Thanks,
Madhu

**Comment by Saketh-Chandra** [comment]
Hello @MadhuDara,

Thank you very much for offering me the opportunity to work at Proximate Technologies.
After much deliberation, I will not be accepting the job, as I have got an internship offer from Honeywell for the next 6 months.
I sincerely appreciate the offer. I wish I could have worked with you, but I couldn't. I'm sorry for letting you down.

Kind regards,
@Saketh-Chandra

**Comment by MadhuDara** [comment]
Hello Saketh,

Hope you are doing great, as mentioned earlier I hope you completed your 6months of internship.
If you are available now please reach me @+1 469-731-3979 to hava a quick decision.

Thanks,
Madhu

**Comment by Saketh-Chandra** [comment]
Hello @MadhuDara,
I'm sorry for letting you down,  I got a full-time offer at Honeywell!
Kind regards,
@Saketh-Chandra.
